### ISSUE TITLE
Clarification on Safer Service Timeouts

### ISSUE THREAD

**Issue by ScotterC** [ankane/slowpoke#24]
In the readme it seems to imply that when using Puma a timeout will kill the process and all the threads. However is that still the case when you're sending [TERM to the process](https://github.com/puma/puma/blob/master/docs/signals.md) which is supposed to "the worker will attempt to finish then exit" ? And if that's the case, what advantages are there from only killing processes if it's within an ActiveRecord code execution?

Thanks for your time.

**Comment by ankane** [comment]
Hi @ScotterC, Slowpoke [uses TERM](https://github.com/ankane/slowpoke/blob/d98700964dd1648acc59915f76e88cc871bae38a/lib/slowpoke.rb#L13-L21) for Puma. It's safest to always exit, but since this will have a significant impact on performance, you can choose to only exit in certain cases (Active Record is just an example of a place I've seen issues if it's interrupted and you don't exit).

**Comment by feliperaul** [comment]
@ankane Came here to ask the same thing as @ScotterC.

I couldn't understand exactly what would be the "significant impact on performance".

Just to be sure: The process will be killed and a new one will be be spawned in it's place by puma, so the worker pool won't get permanently reduced, correct?

If that's the case, what is the impact on performance on the gem's defaults?

Thank you!

**Comment by frenkel** [comment]
For me the impact was that there were no other workers left, so clients had to wait till the new worker was booted.
